# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Joel Winarske
#
# Meson cross-file for ARM Cortex-M bare-metal targets (arm-none-eabi).
# Usage:  meson setup build --cross-file cross/arm-none-eabi.ini

[binaries]
c       = 'arm-none-eabi-gcc'
cpp     = 'arm-none-eabi-g++'
ar      = 'arm-none-eabi-ar'
as      = 'arm-none-eabi-as'
ld      = 'arm-none-eabi-ld'
strip   = 'arm-none-eabi-strip'
size    = 'arm-none-eabi-size'
objcopy = 'arm-none-eabi-objcopy'

[properties]
needs_exe_wrapper = true
# Set your specific CPU / FPU here:
# c_args   = ['-mcpu=cortex-m4', '-mfpu=fpv4-sp-d16', '-mfloat-abi=hard', '-mthumb']
# cpp_args = ['-mcpu=cortex-m4', '-mfpu=fpv4-sp-d16', '-mfloat-abi=hard', '-mthumb']

[host_machine]
system     = 'baremetal'
cpu_family = 'arm'
cpu        = 'cortex-m4'
endian     = 'little'
