# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Joel Winarske
#
# Meson cross-file for RISC-V 32-bit bare-metal targets.
# Usage:  meson setup build --cross-file cross/riscv32-none-elf.ini

[binaries]
c       = 'riscv32-unknown-elf-gcc'
cpp     = 'riscv32-unknown-elf-g++'
ar      = 'riscv32-unknown-elf-ar'
strip   = 'riscv32-unknown-elf-strip'

[properties]
needs_exe_wrapper = true

[host_machine]
system     = 'baremetal'
cpu_family = 'riscv32'
cpu        = 'rv32imac'
endian     = 'little'
