// SPDX-License-Identifier: MIT
// Copyright (c) 2025 LVGL Kft
// Copyright (c) 2026 Joel Winarske
//
// lvgl-cxx — LVGL native C++23 redesign
// Upstream LVGL baseline: v9.5.0
// https://github.com/lvgl/lvgl/releases/tag/v9.5.0
//
// Umbrella header.  Include this file for the complete lvgl-cxx API.
// For C++23 modules support (Phase 6) use:  import lvgl;

#pragma once

#include "lvgl_config.hpp"  // generated by Meson

// ── Miscellaneous primitives
// ──────────────────────────────────────────────────
#include "misc/area.hpp"
#include "misc/color.hpp"
#include "misc/font.hpp"

// ── Core subsystems
// ────────────────────────────────────────────────────────────
#include "core/animation.hpp"
#include "core/display.hpp"
#include "core/draw_buffer.hpp"
#include "core/event.hpp"
#include "core/group.hpp"
#include "core/layer.hpp"
#include "core/object.hpp"
#include "core/observer.hpp"
#include "core/screen.hpp"
#include "core/style.hpp"

// ── Draw / Render
// ────────────────────────────────────────────────────────────
#include "draw/descriptors.hpp"
#include "draw/software_renderer.hpp"

// ── Tick
// ────────────────────────────────────────────────────────────────────
#include "tick/tick.hpp"

// ── Widgets (Phase 5)
// ─────────────────────────────────────────────────────────
#include "widgets/animimage.hpp"
#include "widgets/arc.hpp"
#include "widgets/arclabel.hpp"
#include "widgets/bar.hpp"
#include "widgets/button.hpp"
#include "widgets/buttonmatrix.hpp"
#include "widgets/calendar.hpp"
#include "widgets/canvas.hpp"
#include "widgets/chart.hpp"
#include "widgets/checkbox.hpp"
#include "widgets/container.hpp"
#include "widgets/dropdown.hpp"
#include "widgets/image.hpp"
#include "widgets/imagebutton.hpp"
#include "widgets/keyboard.hpp"
#include "widgets/label.hpp"
#include "widgets/led.hpp"
#include "widgets/line.hpp"
#include "widgets/list.hpp"
#include "widgets/menu.hpp"
#include "widgets/msgbox.hpp"
#include "widgets/roller.hpp"
#include "widgets/scale.hpp"
#include "widgets/slider.hpp"
#include "widgets/span.hpp"
#include "widgets/spinbox.hpp"
#include "widgets/spinner.hpp"
#include "widgets/switch.hpp"
#include "widgets/table.hpp"
#include "widgets/tabview.hpp"
#include "widgets/textarea.hpp"
#include "widgets/tileview.hpp"
#include "widgets/window.hpp"

// ── Drivers (Phase 6) — concepts and input device abstractions
// ─────────────
#include "drivers/concepts.hpp"
#include "drivers/input_device.hpp"
// Platform drivers (SDL2, DRM, evdev, SPI) are included separately
// because they depend on platform-specific libraries.
