// SPDX-License-Identifier: MIT
// Copyright (c) 2025 LVGL Kft
// Copyright (c) 2026 Joel Winarske
//
// lvgl-cxx — LVGL native C++23 redesign
// Upstream LVGL baseline: v9.5.0  https://github.com/lvgl/lvgl/releases/tag/v9.5.0
//
// Umbrella header.  Include this file for the complete lvgl-cxx API.
// For C++23 modules support (Phase 6) use:  import lvgl;

#pragma once

#include "lvgl_config.hpp"          // generated by Meson

// ── Miscellaneous primitives ──────────────────────────────────────────────────
#include "misc/color.hpp"
#include "misc/area.hpp"
#include "misc/font.hpp"
#include "misc/timer.hpp"

// ── Core subsystems ────────────────────────────────────────────────────────────
#include "core/object.hpp"
#include "core/screen.hpp"
#include "core/style.hpp"
#include "core/event.hpp"
#include "core/animation.hpp"
#include "core/group.hpp"
#include "core/observer.hpp"
#include "core/display.hpp"

// ── Widgets ────────────────────────────────────────────────────────────────────
#include "widgets/label.hpp"
#include "widgets/button.hpp"
#include "widgets/slider.hpp"
#include "widgets/arc.hpp"
#include "widgets/bar.hpp"
#include "widgets/switch.hpp"
#include "widgets/checkbox.hpp"
#include "widgets/dropdown.hpp"
#include "widgets/roller.hpp"
#include "widgets/textarea.hpp"
#include "widgets/keyboard.hpp"
#include "widgets/image.hpp"
#include "widgets/animimage.hpp"
#include "widgets/imagebutton.hpp"
#include "widgets/line.hpp"
#include "widgets/canvas.hpp"
#include "widgets/chart.hpp"
#include "widgets/table.hpp"
#include "widgets/buttonmatrix.hpp"
#include "widgets/scale.hpp"
#include "widgets/led.hpp"
#include "widgets/list.hpp"
#include "widgets/msgbox.hpp"
#include "widgets/calendar.hpp"
#include "widgets/span.hpp"
#include "widgets/spinbox.hpp"
#include "widgets/spinner.hpp"
#include "widgets/arclabel.hpp"
#include "widgets/tabview.hpp"
#include "widgets/tileview.hpp"
#include "widgets/window.hpp"
#include "widgets/menu.hpp"
