// SPDX-License-Identifier: MIT
// Copyright (c) 2025 LVGL Kft
// Copyright (c) 2026 Joel Winarske
//
// lvgl-cxx — misc/font_fmt_txt.hpp
// Upstream LVGL baseline: v9.5.0
// https://github.com/lvgl/lvgl/releases/tag/v9.5.0
//
// FmtTxtFont — Font class that wraps LVGL's lv_font_fmt_txt format.
// Supports FORMAT0_TINY and SPARSE_TINY cmap lookups, class-based kerning,
// and 1/2/4/8 bpp glyph bitmaps.
//
// This allows direct reuse of the data arrays generated by lv_font_conv.

#pragma once

#include <algorithm>
#include <cstdint>
#include <span>

#include "font.hpp"

namespace lv {

// ── Glyph descriptor entry (matches lv_font_fmt_txt_glyph_dsc_t) ───────────
struct FmtTxtGlyphDsc {
  uint32_t bitmap_index;
  uint16_t adv_w;  // 8.4 fixed point (divide by 16 to get pixels)
  uint8_t box_w;
  uint8_t box_h;
  int8_t ofs_x;
  int8_t ofs_y;
};

// ── Character map types ─────────────────────────────────────────────────────
enum class CmapType : uint8_t {
  Format0Tiny,  // contiguous range, direct mapping
  Format0Full,  // contiguous range with offset list
  SparseTiny,   // sparse set, binary search, direct offset
  SparseFull,   // sparse set, binary search, offset list
};

struct FmtTxtCmap {
  uint32_t range_start;
  uint32_t range_length;
  uint16_t glyph_id_start;
  const uint16_t* unicode_list;       // for sparse types
  const uint16_t* glyph_id_ofs_list;  // for full types
  uint16_t list_length;
  CmapType type;
};

// ── Kern classes ────────────────────────────────────────────────────────────
struct FmtTxtKernClasses {
  const int8_t* class_pair_values;
  const uint8_t* left_class_mapping;
  const uint8_t* right_class_mapping;
  uint8_t left_class_cnt;
  uint8_t right_class_cnt;
};

// ── Format descriptor (matches lv_font_fmt_txt_dsc_t) ───────────────────────
struct FmtTxtDsc {
  const uint8_t* glyph_bitmap;
  const FmtTxtGlyphDsc* glyph_dsc;
  std::span<const FmtTxtCmap> cmaps;
  const FmtTxtKernClasses* kern_classes;  // nullptr if no kerning
  uint16_t kern_scale;                    // typically 16 (12.4 format)
  uint8_t bpp;                            // 1, 2, 4, or 8
};

// ── FmtTxtFont ──────────────────────────────────────────────────────────────
class FmtTxtFont final : public Font {
 public:
  explicit FmtTxtFont(const FmtTxtDsc& dsc, int32_t line_h, int32_t base)
      : dsc_(dsc), line_h_(line_h), base_(base) {}

  [[nodiscard]] bool get_glyph_dsc(GlyphDsc& out,
                                   uint32_t unicode_letter) const override {
    const auto glyph_id = lookup_glyph_id(unicode_letter);
    if (glyph_id == 0)
      return false;

    const auto& g = dsc_.glyph_dsc[glyph_id];
    out.advance_w = static_cast<uint16_t>(g.adv_w >> 4);  // 8.4 → pixels
    out.box_w = g.box_w;
    out.box_h = g.box_h;
    out.ofs_x = g.ofs_x;
    out.ofs_y = g.ofs_y;
    out.bpp = dsc_.bpp;
    out.bitmap = &dsc_.glyph_bitmap[g.bitmap_index];
    return true;
  }

  [[nodiscard]] int32_t line_height() const noexcept override {
    return line_h_;
  }
  [[nodiscard]] int32_t base_line() const noexcept override { return base_; }

  // Get kern adjustment between two Unicode characters (in pixels)
  [[nodiscard]] int32_t get_kern(uint32_t left, uint32_t right) const {
    if (!dsc_.kern_classes)
      return 0;

    const auto lid = lookup_glyph_id(left);
    const auto rid = lookup_glyph_id(right);
    if (lid == 0 || rid == 0)
      return 0;

    const auto& kc = *dsc_.kern_classes;
    const uint8_t lc = kc.left_class_mapping[lid];
    const uint8_t rc = kc.right_class_mapping[rid];
    if (lc == 0 || rc == 0)
      return 0;

    const auto idx = static_cast<int>((lc - 1) * kc.right_class_cnt + (rc - 1));
    const int8_t raw = kc.class_pair_values[idx];
    return (static_cast<int32_t>(raw) * dsc_.kern_scale) >> 4;
  }

 private:
  [[nodiscard]] uint16_t lookup_glyph_id(uint32_t unicode) const {
    for (const auto& cm : dsc_.cmaps) {
      if (unicode < cm.range_start)
        continue;
      const uint32_t rcp = unicode - cm.range_start;
      if (rcp >= cm.range_length)
        continue;

      switch (cm.type) {
        case CmapType::Format0Tiny:
          return static_cast<uint16_t>(cm.glyph_id_start + rcp);

        case CmapType::Format0Full:
          if (cm.glyph_id_ofs_list)
            return static_cast<uint16_t>(cm.glyph_id_start +
                                         cm.glyph_id_ofs_list[rcp]);
          return 0;

        case CmapType::SparseTiny: {
          if (!cm.unicode_list)
            return 0;
          // Binary search for rcp in unicode_list
          const auto* begin = cm.unicode_list;
          const auto* end = begin + cm.list_length;
          const auto* it =
              std::lower_bound(begin, end, static_cast<uint16_t>(rcp));
          if (it != end && *it == static_cast<uint16_t>(rcp)) {
            return static_cast<uint16_t>(cm.glyph_id_start +
                                         static_cast<uint16_t>(it - begin));
          }
          return 0;
        }

        case CmapType::SparseFull: {
          if (!cm.unicode_list || !cm.glyph_id_ofs_list)
            return 0;
          const auto* begin = cm.unicode_list;
          const auto* end = begin + cm.list_length;
          const auto* it =
              std::lower_bound(begin, end, static_cast<uint16_t>(rcp));
          if (it != end && *it == static_cast<uint16_t>(rcp)) {
            const auto idx = static_cast<std::size_t>(it - begin);
            return static_cast<uint16_t>(cm.glyph_id_start +
                                         cm.glyph_id_ofs_list[idx]);
          }
          return 0;
        }
      }
    }
    return 0;
  }

  FmtTxtDsc dsc_;
  int32_t line_h_;
  int32_t base_;
};

}  // namespace lv
