// SPDX-License-Identifier: MIT
// Copyright (c) 2025 LVGL Kft
// Copyright (c) 2026 Joel Winarske
//
// Phase 0 smoke test — verifies the build infrastructure compiles and that
// the generated config header is reachable.  Ported to Google Test.

#include <gtest/gtest.h>

#include "lvgl_config.hpp"  // generated by Meson from lvgl_config.hpp.in

TEST(Smoke, VersionMacrosDefined) {
    EXPECT_GE(LVGLCXX_VERSION_MAJOR, 1);
    EXPECT_GE(LVGLCXX_VERSION_MINOR, 0);
    EXPECT_GE(LVGLCXX_VERSION_PATCH, 0);
}

TEST(Smoke, LvglBaselineIsV950) {
    // Ensures the wrap and config always reference the correct upstream release.
    std::string_view baseline{LVGLCXX_LVGL_BASELINE};
    EXPECT_EQ(baseline, "v9.5.0");
}

TEST(Smoke, ExactlyOneColorFormatSelected) {
    int formats_selected = LVGLCXX_COLOR_ARGB8888 + LVGLCXX_COLOR_RGB888 +
                           LVGLCXX_COLOR_RGB565 + LVGLCXX_COLOR_L8;
    EXPECT_EQ(formats_selected, 1);
}
