// SPDX-License-Identifier: MIT
// Copyright (c) 2025 LVGL Kft
// Copyright (c) 2026 Joel Winarske
//
// Phase 0 smoke test — verifies the build infrastructure compiles and that
// the generated config header is reachable.  No lvgl-cxx objects are created
// yet (library sources are empty in Phase 0).

#include <catch2/catch_test_macros.hpp>
#include "lvgl_config.hpp"   // generated by Meson from lvgl_config.hpp.in

TEST_CASE("version macros are defined", "[smoke]") {
    REQUIRE(LVGLCXX_VERSION_MAJOR >= 1);
    REQUIRE(LVGLCXX_VERSION_MINOR >= 0);
    REQUIRE(LVGLCXX_VERSION_PATCH >= 0);
}

TEST_CASE("LVGL baseline is v9.5.0", "[smoke]") {
    // Ensures the wrap and config always reference the correct upstream release.
    std::string_view baseline{LVGLCXX_LVGL_BASELINE};
    REQUIRE(baseline == "v9.5.0");
}

TEST_CASE("exactly one color format is selected", "[smoke]") {
    int formats_selected =
        LVGLCXX_COLOR_ARGB8888 +
        LVGLCXX_COLOR_RGB888   +
        LVGLCXX_COLOR_RGB565   +
        LVGLCXX_COLOR_L8;
    REQUIRE(formats_selected == 1);
}
